# Generated by Django 4.2.27 on 2026-01-20 16:34

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('COAG', 'Coordenação de Administração Geral'), ('GEAD', 'Gerência de Administração'), ('NUINF', 'Núcleo de Informática'), ('NUMAP', 'Núcleo de Material e Patrimônio'), ('GEOFIN', 'Gerência de Orçamento e Finanças'), ('GEPES', 'Gerência de Pessoas'), ('CODES', 'Coordenação de Desenvolvimento'), ('DIDOT', 'Diretoria de Desenvolvimento e Territorial'), ('GETEDEC', 'Gerência de Gestão do Território e Desevolvimento Econômico'), ('DIART', 'Diretoria de Articulação'), ('GEPSCEL', 'Gerência de Políticas Sociais, Cultura, Esporte e Lazer'), ('COLOM', 'Coordenação de Licenciamento, Obras e Manutenção'), ('DIALIC', 'Diretoria de Aprovação e Licenciamento'), ('GELOAE', 'Gerência de Licenciamento de Obras e Atividades Econômicas'), ('GEAPRO', 'Gerência de Elaboração e Aprovação de Projetos'), ('DIROB', 'Diretoria de Obras'), ('GEOB', 'Gerência de Obras'), ('GEMAC', 'Gerência de Manutenção e Conservação'), ('ASCOM', 'Assessoria de comunicação'), ('ASTEC', 'Assessoria Técnica'), ('ASPLAN', 'Assessoria de Planejamento'), ('GAB', 'Gabinete'), ('OUV', 'Ouvidoria'), ('JSM', 'Junta de Serviço Militar')], max_length=10, verbose_name='Departamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Horário de Entrada')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='core.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='phone',
            constraint=models.UniqueConstraint(fields=('client', 'number'), name='unique_phone'),
        ),
    ]
