# Generated by Django 4.2.27 on 2026-05-30 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="citizen",
            name="unique_active_cpf",
        ),
        migrations.RemoveField(
            model_name="citizen",
            name="status",
        ),
        migrations.RemoveField(
            model_name="historicalcitizen",
            name="status",
        ),
        migrations.AlterField(
            model_name="citizen",
            name="cpf",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{11}$", "CPF must have exactly 11 digits"
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="entrance",
            name="citizen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entrances",
                to="core.citizen",
                verbose_name="Cidadão",
            ),
        ),
    ]
