# Generated by Django 4.2.27 on 2026-01-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260127_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('CANCELADO', 'Cancelado')], default='REGULAR', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('CANCELADO', 'Cancelado')], default='REGULAR', max_length=20, verbose_name='Status'),
        ),
    ]
