# Generated by Django 4.2.27 on 2026-06-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_citizen_unique_active_cpf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
        ),
        migrations.AlterField(
            model_name="citizen",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="historicalcitizen",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Criado em"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcitizen",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Atualizado em"
            ),
        ),
    ]
