import pytest
from sqlalchemy.exc import IntegrityError
from datetime import datetime

from services import SystemService
from models import Client, Entrance
from extensions import db
from utils import sanitize_many


@pytest.mark.parametrize('name', [
    " ", "    ",
])
def test_is_valid_name_with_invalid_name(name):
    """Tests the method 'SystemService.is_valid_name()'.
    It should return False for invalid names.
    """
    assert not SystemService.is_valid_name(name)


@pytest.mark.parametrize('name', [
    "José", "Gabriel", "Manu"
])
def test_is_valid_name_with_valid_name(name):
    """Tests the method 'SystemService.is_valid_name()'.
    It should return True for valid names.
    """
    assert SystemService.is_valid_name(name)


@pytest.mark.parametrize('rg', [
    " ", "    ",
])
def test_is_valid_rg_with_invalid_rg(rg):
    """Tests the method 'SystemService.is_valid_rg()'.
    It should return False for invalid RG values.
    """
    assert not SystemService.is_valid_rg(rg)


def test_is_valid_rg_with_valid_rg(faker_obj):
    """Tests the method 'SystemService.is_valid_rg()'.
    It should return True for valid RG values.
    """
    for rg in [faker_obj.rg() for _ in range(10)]:
        assert SystemService.is_valid_rg(rg)


@pytest.mark.parametrize('cpf', [
    "366.309.641-61",
    "133.899.368-24",
    "174.468.700-53",
    "23258216500",
    "39369638009",
])
def test_is_valid_cpf_with_invalid_cpf(cpf):
    """Tests the method 'SystemService.is_valid_cpf()'.
    It should return False for invalid CPF values.
    """
    assert not SystemService.is_valid_cpf(cpf)


def test_is_valid_cpf_with_valid_cpf(faker_obj):
    """Tests the method 'SystemService.is_valid_cpf()'.
    It should return True for valid CPFs.
    """
    for cpf in [faker_obj.cpf() for _ in range(10)]:
        assert SystemService.is_valid_cpf(cpf)


@pytest.mark.parametrize("phone", [
    "11 12345678",
    "21 87654321",
    "31 912345678",
    "41 934567890",
    "51 923456781",
])
def test_is_valid_phone_with_valid_numbers(phone):
    """Tests the method 'SystemService.is_valid_phone()'.
    It should return True for valid phone numbers.
    """
    assert SystemService.is_valid_phone(phone)


@pytest.mark.parametrize("phone", [
    "1112345678",
    "11 1234567",
    "11 123456789",
    "11 9912345678",
    "1 912345678",
    "aa 912345678",
    "11 9abcdefgh",
    "11-912345678",
    "11912345678",
    "11 9 12345678",
])
def test_is_valid_phone_with_invalid_numbers(phone):
    """Tests the method 'SystemService.is_valid_phone()'.
    It should return False for invalid phone numbers.
    """
    assert not SystemService.is_valid_phone(phone)


def test_is_valid_birth_date_with_valid_dates(faker_obj):
    """Tests the method 'SystemService.is_valid_birth_date()'.
    It should return True for valid birth dates generated by Faker.
    """
    for _ in range(10):
        birth_date = faker_obj.date_of_birth(
            maximum_age=SystemService.MAX_AGE
        ).strftime("%d/%m/%Y")

        assert SystemService.is_valid_birth_date(birth_date)


@pytest.mark.parametrize("birth_date", [
    "", " ", "32/01/2000", "00/10/2000",
    "15/13/2000", "15/00/2000", "15-10-2000",
    "abcd", "2000/10/15", "31/02/2020",
    (datetime.today().replace(year=datetime.today().year + 1).strftime("%d/%m/%Y")),
    (datetime.today().replace(year=datetime.today().year - (SystemService.MAX_AGE + 10)).strftime("%d/%m/%Y")),
])
def test_is_valid_birth_date_with_invalid_dates(birth_date):
    """Tests the method 'SystemService.is_valid_birth_date()'.
    It should return False for invalid birth dates.
    """
    assert not SystemService.is_valid_birth_date(birth_date)


def test_find_client_by_id(clients_objs):
    """Tests the method 'SystemService.find_client()'.
    It should return the Client instance when searching by ID, CPF or RG.
    """

    for client in clients_objs:
        id, cpf, rg = client.id, client.cpf, client.rg

        for info in (id, cpf, rg):
            found = SystemService.find_client(info)

            assert found.id == client.id


def test_find_client_returns_none_when_not_found():
    """Tests the method 'SystemService.find_client()'.
    It should return 'None' when no client matches ID, RG, or CPF.
    """

    assert not SystemService.find_client("00000000000")





